apiVersion: v1
kind: Service
metadata:
  name: k8s-external-user-mysql-service
spec:
  ports:
    - port: 3306

---

apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-external-user-mysql-service
subsets:
  - addresses:
      - ip: 172.30.1.29
    ports:
      - port: 13306